name = "Simply Optimized"
author = "HyperSoop"
version = "1.19.x-2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81b72221937c187d2fc077765f109254d9d988f0723eb2b89a583921f98205d9"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
